---
title: "OpenGender Usage"
format: html
editor: visual
---

```{r setup}
library(opengender)
```

```{r list-available}
# show available dictionaries
list_dicts()
```

```{r show-dictionary}
show_dict("kantro")
```

```{r test-data}
# common baby names 1923-2022 
#-- from https://www.ssa.gov/oact/babynames/decades/century.html
ssa_baby_names.df <- structure(list( firstname = c("James", "Robert", "John", "Michael", 
"David", "William", "Richard", "Joseph", "Thomas", "Christopher", 
"Charles", "Daniel", "Matthew", "Anthony", "Mark", "Donald", 
"Steven", "Andrew", "Paul", "Joshua", "Kenneth", "Kevin", "Brian", 
"George", "Timothy", "Ronald", "Jason", "Edward", "Jeffrey", 
"Ryan", "Jacob", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", 
"Larry", "Justin", "Scott", "Brandon", "Benjamin", "Samuel", 
"Gregory", "Alexander", "Patrick", "Frank", "Raymond", "Jack", 
"Dennis", "Jerry", "Tyler", "Aaron", "Jose", "Adam", "Nathan", 
"Henry", "Zachary", "Douglas", "Peter", "Kyle", "Noah", "Ethan", 
"Jeremy", "Walter", "Christian", "Keith", "Roger", "Terry", "Austin", 
"Sean", "Gerald", "Carl", "Harold", "Dylan", "Arthur", "Lawrence", 
"Jordan", "Jesse", "Bryan", "Billy", "Bruce", "Gabriel", "Joe", 
"Logan", "Alan", "Juan", "Albert", "Willie", "Elijah", "Wayne", 
"Randy", "Vincent", "Mason", "Roy", "Ralph", "Bobby", "Russell", 
"Bradley", "Philip", "Eugene", "Mary", "Patricia", "Jennifer", 
"Linda", "Elizabeth", "Barbara", "Susan", "Jessica", "Sarah", 
"Karen", "Lisa", "Nancy", "Betty", "Sandra", "Margaret", "Ashley", 
"Kimberly", "Emily", "Donna", "Michelle", "Carol", "Amanda", 
"Melissa", "Deborah", "Stephanie", "Dorothy", "Rebecca", "Sharon", 
"Laura", "Cynthia", "Amy", "Kathleen", "Angela", "Shirley", "Brenda", 
"Emma", "Anna", "Pamela", "Nicole", "Samantha", "Katherine", 
"Christine", "Helen", "Debra", "Rachel", "Carolyn", "Janet", 
"Maria", "Catherine", "Heather", "Diane", "Olivia", "Julie", 
"Joyce", "Victoria", "Ruth", "Virginia", "Lauren", "Kelly", "Christina", 
"Joan", "Evelyn", "Judith", "Andrea", "Hannah", "Megan", "Cheryl", 
"Jacqueline", "Martha", "Madison", "Teresa", "Gloria", "Sara", 
"Janice", "Ann", "Kathryn", "Abigail", "Sophia", "Frances", "Jean", 
"Alice", "Judy", "Isabella", "Julia", "Grace", "Amber", "Denise", 
"Danielle", "Marilyn", "Beverly", "Charlotte", "Natalie", "Theresa", 
"Diana", "Brittany", "Doris", "Kayla", "Alexis", "Lori", "Marie"
), Female = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)), row.names = c(NA, 
-200L), class = "data.frame")


```

```{r gender-coding}
library(magrittr)

names_sample.df <- ssa_baby_names.df %>%
  dplyr::slice_sample(n=1000, replace=TRUE)

names_sample.df %<>% 
  dplyr::bind_rows(tibble::tibble(firstname=c("Wozzleface","Hanah")))

names_sample.df %>%  
  add_gender_predictions(
              dicts = "kantro",
              col_map=c(given = "firstname") ) -> res

res
```

```{r gender-coding-api}
library(magrittr)

names_sample.df <- ssa_baby_names.df %>%
  dplyr::slice_sample(n=10, replace=FALSE)

names_sample.df %<>% 
  dplyr::bind_rows(tibble::tibble(firstname=c("Wozzleface","Hanah")))

names_sample.df %>% 
  add_gender_predictions(
              dicts = "genderize",
              col_map=c(given = "firstname") ) -> res

res
```

```{r point-estimation}

res %>% dplyr::select("og_pr_F") %>% gender_mean()
res %>% dplyr::select("og_details") %>% gender_mean(simplify_output = "tidy")

res %>% dplyr::mutate(AM=stringr::str_starts(firstname,"[A-M]")) %>%
  dplyr::group_by(AM) %>% dplyr::summarise(prop_F= mean(og_pr_F,na.rm=TRUE))

res %>% dplyr::mutate(AM=stringr::str_starts(firstname,"[A-M]")) %>%
  dplyr::group_by(AM) %>% dplyr::summarise(prop_F = gender_mean(og_pr_F,simplify_output="scalar"))

res %>% dplyr::mutate(AM=stringr::str_starts(firstname,"[A-M]")) %>%
  dplyr::group_by(AM) %>% dplyr::summarise(prop_genders = gender_mean(og_pr_F,simplify_output="row")) %>% tidyr::unpack(prop_genders)

res %>% dplyr::mutate(AM=stringr::str_starts(firstname,"[A-M]")) %>%
  dplyr::group_by(AM) %>% dplyr::summarise(prop_F = list( gender_mean(og_pr_F))) %>% tidyr::unnest(prop_F)
```

```{r estimates-with-uncertainty}

res %>% dplyr::select("og_details") %>%
  gender_estimate(simplify_output="scalar", estimates=c("mean","sd"))

res %>% 
  dplyr::mutate(AM=stringr::str_starts(firstname,"[A-M]")) %>%
  dplyr::group_by(AM) %>% 
  dplyr::summarise(gender_estimates =
        gender_estimate(og_pr_F,simplify_output="row",
                        estimates=c("mean","sd"))) %>% 
  tidyr::unpack(gender_estimates)

res %>% dplyr::select("og_details") %>%
  dplyr::slice_sample(n=100) %>%
  gender_estimate()
```

```{r user-dict}
list_dicts()
clean_dicts() 
list_dicts()
data(kantro)
bizarro <- kantro %>% 
  dplyr::mutate(gender= dplyr::case_match(gender, "M"~"F", "F"~"M"))
try(manage_local_dicts(bizarro,name="kantro", description="reversed kantro"))
manage_local_dicts(bizarro,name="bizarro", description="reversed kantro", force=TRUE)
list_dicts()
show_dict("bizarro")
```

```{r wgen-dictionary}

show_dict("wgen2")

# match to aggregate of countries
names_sample.df %>% 
  add_gender_predictions(
              dicts = "wgen2",
              col_map=c(given = "firstname") ) 
```

```{r matching-over-time-samp}

load_dict("ssa")
show_dict("ssa") -> ssa.df
ssa.df %>% filter(given=="leslie") %>%
  filter(year<10000) %>%
  ggplot(aes(x=year,y=pr_F)) + geom_point()

ssa.df %>% filter(year < 10000, n>50) %>% pull(given) %>% unique() %>% sample(500,replace=TRUE) -> sampleg
ssa.df %>% pull(year) %>% unique() %>% sample(500,replace=TRUE) -> samplet

mixedyear.df <- tibble(given=sampleg,year=samplet)

mixedyear.df  %<>% 
  add_gender_predictions(
              dicts = "ssa",
              col_map=c(given = "given") ) 

mixedyear.df
```

```{r input-data-for-org-matching}

# WOS publications for sociology departments
socdepts.df <- structure(list(department = c("Ucla Department Of Sociology", 
"University Of Toronto Department Of Sociology", "University Of Wisconsin Madison Department Of Sociology", 
"University Of Oxford Department Of Sociology", "Harvard University Department Of Sociology", 
"Copenhagen University Department Of Sociology", "Princeton University Department Of Sociology", 
"University Of California Berkeley Department Of Sociology", 
"New York University Department Of Sociology", "The University Of North Carolina At Chapel Hill Department Of Sociology", 
"University Of Cologne Institute Of Sociology And Social Psychology", 
"University Of Oslo Department Of Sociology And Human Geography", 
"The Ohio State University Department Of Sociology", "University Of Pennsylvania Department Of Sociology", 
"The Pennsylvania State University Department Of Sociology And Criminology", 
"University Of California Irvine Department Of Sociology", "Duke University Department Of Sociology", 
"The University Of British Columbia Department Of Sociology", 
"The University Of Texas At Austin Department Of Sociology", 
"University Of Michigan Department Of Sociology", "Indiana University Bloomington Department Of Sociology", 
"Stanford University Department Of Sociology", "Stockholm University Department Of Sociology", 
"University Of Chicago Department Of Sociology", "Utrecht University Department Of Sociology", 
"Northwestern University Department Of Sociology", "University Of Trento Department Of Sociology And Social Research", 
"The University Of Manchester Sociology", "University Of Amsterdam Department Of Sociology And Anthropology", 
"The London School Of Economics And Political Science Department Of Sociology", 
"Brown University Department Of Sociology", "University Of Maryland At College Park Department Of Sociology", 
"The University Of Hong Kong Department Of Sociology", "University Of Cambridge Department Of Sociology", 
"Cornell University Department Of Sociology", "Columbia University Department Of Sociology", 
"Radboud University Department Of Sociology", "Boston University Department Of Sociology", 
"University Of Minnesota Twin Cities Department Of Sociology", 
"University Of Southern California Department Of Sociology", 
"Boston College Sociology Department", "Mcgill University Department Of Sociology", 
"University Of Bristol School Of Sociology Politics And International Studies", 
"Vanderbilt University Department Of Sociology", "Purdue University Department Of Sociology", 
"University Of California Davis Department Of Sociology", "University Of Notre Dame Department Of Sociology", 
"University Of York Department Of Sociology", "Yale University Department Of Sociology", 
"University Of Gothenburg Department Of Sociology And Work Science", 
"University Of Massachusetts Amherst Department Of Sociology", 
"The Chinese University Of Hong Kong Department Of Sociology", 
"University Of Essex Department Of Sociology", "University Of Haifa Department Of Sociology", 
"Tel Aviv University Department Of Sociology And Anthropology", 
"Baylor University Department Of Sociology", "Bielefeld University Faculty Of Sociology", 
"Bowling Green State University Department Of Sociology", "Umea University Sociology Department", 
"University At Buffalo Department Of Sociology", "Michigan State University Department Of Sociology", 
"Rice University Department Of Sociology", "University Of California Santa Barbara Department Of Sociology", 
"University Of Connecticut Department Of Sociology", "National University Of Singapore Department Of Sociology And Anthropology", 
"Rutgers New Brunswick Department Of Sociology", "University Of California Riverside Department Of Sociology", 
"University Of Warwick Department Of Sociology", "Bar Ilan University Department Of Sociology And Anthropology", 
"Tilburg University Department Of Sociology", "Vu Amsterdam Department Of Sociology", 
"Emory University Department Of Sociology", "Goldsmiths University Of London Department Of Sociology", 
"Johns Hopkins University Department Of Sociology", "Nc State University Department Of Sociology And Anthropology", 
"Norwegian University Of Science And Technology Department Of Sociology And Political Science", 
"University Of Colorado Boulder Department Of Sociology", "University Of Kansas Department Of Sociology", 
"University Of Washington Department Of Sociology", "Western University Department Of Sociology", 
"Lancaster University Department Of Sociology", "Northeastern University Department Of Sociology And Anthropology", 
"The University Of Arizona School Of Sociology", "The University Of Iowa Department Of Sociology And Criminology", 
"York University Department Of Sociology", "Hong Kong Baptist University Department Of Sociology", 
"Lingnan University Department Of Sociology Social Policy", "Louisiana State University Department Of Sociology", 
"Texas A M University Department Of Sociology", "The University Of Utah Department Of Sociology", 
"Unc Charlotte Department Of Sociology", "University Of Kent School Of Social Policy Sociology And Social Research", 
"Hamilton College Department Of Sociology", "Hebrew University Of Jerusalem Department Of Sociology And Anthropology", 
"Mcmaster University Department Of Sociology", "The University Of Alabama At Birmingham Department Of Sociology", 
"The University Of Oklahoma Department Of Sociology", "University Of California San Diego Department Of Sociology", 
"University Of North Texas Department Of Sociology", "University Of Rome La Sapienza Faculty Of Political Sciences Sociology And Communication", 
"Washington State University Department Of Sociology", "Colorado State University Department Of Sociology", 
"Florida State University Department Of Sociology", "Portland State University Department Of Sociology", 
"Renmin University Of China School Of Sociology And Population Studies", 
"University Of Florida Department Of Sociology Criminology And Law", 
"University Of Georgia Department Of Sociology", "University Of Sussex School Of Law Politics And Sociology", 
"Uppsala University Department Of Sociology", "Zhejiang University Department Of Sociology", 
"Australian National University School Of Sociology", "City University Of London Department Of Sociology And Criminology", 
"Free University Of Berlin Institute Of Sociology", "Oklahoma State University Department Of Sociology", 
"University Of Bern Institute Of Sociology", "University Of Calgary Department Of Sociology", 
"University Of Milan Bicocca Department Of Sociology And Social Research", 
"University Of New Mexico Department Of Sociology", "University Of South Carolina Department Of Sociology", 
"Iowa State University Department Of Sociology And Criminal Justice", 
"Lund University Department Of Sociology", "Newcastle University School Of Geography Politics And Sociology", 
"Uio Department Of Criminology And Sociology Of Law", "University College Dublin School Of Sociology", 
"University Of Alberta Department Of Sociology", "University Of Antwerp Department Of Sociology", 
"University Of Bamberg Department Of Sociology", "University Of Delaware Department Of Sociology And Criminal Justice", 
"University Of Illinois Chicago Department Of Sociology", "University Of Nottingham School Of Sociology And Social Policy", 
"University Of Padua Department Of Philosophy Sociology Education And Applied Psychology", 
"University Of South Florida Department Of Sociology", "Wayne State University Department Of Sociology", 
"Manchester Metropolitan University Department Of Sociology", 
"Monash University Sociology", "National Taiwan University Department Of Sociology", 
"Suny Geneseo Department Of Sociology", "Syracuse University Department Of Sociology", 
"The University Of Tennessee Knoxville Department Of Sociology", 
"Tulane University Department Of Sociology", "University Of Bergen Department Of Sociology", 
"University Of Duisburg Essen Institute Of Sociology", "University Of Kentucky Department Of Sociology", 
"University Of Macau Department Of Sociology", "University Of Nebraska Lincoln Department Of Sociology", 
"University Of Oregon Department Of Sociology", "University Of Vienna Department Of Sociology", 
"University Of Virginia Department Of Sociology", "Wake Forest University Department Of Sociology", 
"Autonomous University Of Barcelona Department Of Sociology", 
"Autonomous University Of Barcelona Faculty Of Political Sciences And Sociology", 
"Fudan University Department Of Sociology", "Jagiellonian University In Kraków Institute Of Sociology", 
"Mississippi State University Department Of Sociology", "The University Of Edinburgh Sociology", 
"University Of Cincinnati Department Of Sociology", "University Of Hawai I At Manoa Department Of Sociology", 
"University Of Leeds School Of Sociology And Social Policy", 
"University Of Liverpool Department Of Sociology Social Policy And Criminology", 
"University Of Missouri Department Of Sociology", "Utah State University Department Of Sociology Social Work And Anthropology", 
"Wageningen University Research Rural Sociology Group", "American University Department Of Sociology", 
"Aston University Department Of Sociology And Policy", "Koc University Department Of Sociology", 
"Loyola University Chicago Department Of Sociology", "Shanghai University School Of Sociology And Political Science", 
"The Pennsylvania State University Department Of Agricultural Economics Sociology And Education", 
"The University Of Sydney Department Of Sociology And Social Policy", 
"University Of Barcelona Department Of Sociology", "University Of Frankfurt Department Of Sociology", 
"University Of Graz Department Of Sociology", "University Of Miami Department Of Sociology And Criminology", 
"University Of Surrey Department Of Sociology", "University Of Sussex Department Of Sociology", 
"University Of Victoria Department Of Sociology", "University Of Wisconsin Milwaukee Department Of Sociology", 
"Virginia Polytechnic Institute And State University Department Of Sociology", 
"Ben Gurion University Of The Negev Department Of Sociology And Anthropology", 
"George Mason University Department Of Sociology And Anthropology", 
"Heidelberg University Max Weber Institute Of Sociology", "Memorial University Of Newfoundland Department Of Sociology", 
"National Chengchi University Department Of Sociology", "Santa Clara University Department Of Sociology", 
"The University Of Memphis Department Of Sociology", "University Of Exeter Department Of Sociology Philosophy And Anthropology", 
"University Of Glasgow Sociology", "University Of Konstanz Department Of History Sociology Empirical Educational Research And Sport Science", 
"University Of Mississippi Department Of Sociology And Anthropology", 
"University Of Portsmouth School Of Education And Sociology", 
"University Of Tübingen Department Of Sociology", "Xiamen University School Of Sociology And Anthropology", 
"Florida Atlantic University Department Of Sociology", "Innsbruck School Of Political Science And Sociology", 
"Kansai University Faculty Of Sociology Graduate School Of Sociology", 
"Leibniz University Hannover Institute For Sociology", "Miami University Department Of Sociology And Gerontology", 
"Nanjing University Department Of Sociology", "Renmin University Of China Department Of Sociology", 
"Sun Yat Sen University School Of Sociology And Anthropology", 
"Unc Greensboro Department Of Sociology", "University Of Arkansas Department Of Sociology And Criminology", 
"University Of Birmingham Department Of Social Policy Sociology And Criminology", 
"University Of Bonn Institute Of Political Science And Sociology", 
"University Of California Santa Cruz Department Of Sociology", 
"University Of Göttingen Institute For Sociology", "University Of Houston Department Of Sociology", 
"University Of Konstanz Department Of Sociology", "University Of Mannheim Department Of Sociology", 
"University Of Massachusetts Lowell Department Of Sociology", 
"University Of Neuchâtel Institute Of Sociology", "University Of Wisconsin Madison Department Of Community And Environmental Sociology", 
"American University Of Beirut Department Of Sociology Anthropology And Media Studies", 
"Auburn University Department Of Agricultural Economics And Rural Sociology", 
"Autonomous University Of Madrid Department Of Sociology", "Carleton University Department Of Sociology And Anthropology", 
"Cornell University Department Of Development Sociology", "East China University Of Science And Technology Department Of Sociology", 
"East Tennessee State University Department Of Sociology And Anthropology", 
"Friedrich Schiller University Jena Institute Of Sociology", 
"Johannes Gutenberg University Mainz Institute Of Sociology", 
"Leiden University Institute Of Cultural Anthropology And Development Sociology", 
"Loughborough University Department Of Criminology Sociology And Social Policy", 
"Macquarie University Department Of Sociology", "Montana State University Department Of Sociology And Anthropology", 
"Oakland University Department Of Sociology Anthropology Social Work And Criminal Justice", 
"Seoul National University Department Of Sociology", "Shandong University Department Of Sociology", 
"Sun Yat Sen University Department Of Sociology And Social Work", 
"The Catholic University Of America Department Of Sociology", 
"The University Of Adelaide Department Of Sociology Criminology And Gender Studies", 
"The University Of Arizona Department Of Sociology", "The University Of Texas Arlington Department Of Sociology And Anthropology", 
"The University Of Texas At El Paso Department Of Sociology Anthropology", 
"The University Of Texas At San Antonio Department Of Sociology", 
"Tsinghua University Department Of Sociology", "University Of Agder Department Of Sociology And Social Work", 
"University Of Crete Department Of Sociology", "University Of Denver Department Of Sociology And Criminology", 
"University Of Geneva Department Of Sociology", "University Of Guelph Department Of Sociology And Anthropology", 
"University Of Idaho Department Of Agricultural Economics And Rural Sociology", 
"University Of Innsbruck Institute For Sociology", "University Of Leicester Department Of Sociology", 
"University Of Nevada Las Vegas Department Of Sociology", "University Of New Hampshire Department Of Sociology", 
"University Of North Florida Department Of Sociology Anthropology And Social Work", 
"University Of Richmond Department Of Sociology Anthropology", 
"University Of The Aegean Department Of Sociology", "University Of Waterloo Department Of Sociology And Legal Studies", 
"Virginia Commonwealth University Department Of Sociology", "Western Washington University Department Of Sociology", 
"Airlangga University Department Of Sociology", "Bogazici University Department Of Sociology", 
"Brock University Department Of Sociology", "Cal State East Bay Department Of Sociology", 
"California State University Long Beach Department Of Sociology", 
"Case Western Reserve University Department Of Sociology", "Central China Normal University School Of Sociology", 
"Chapman University Department Of Sociology", "College Of The Holy Cross Department Of Sociology And Anthropology", 
"Complutense University Of Madrid Faculty Of Political Sciences And Sociology", 
"Covenant University Department Of Sociology", "Delaware State University Department Of Sociology And Criminal Justice", 
"East Carolina University Department Of Sociology", "Georgetown University Department Of Sociology", 
"Georgia Southern University Department Of Sociology And Anthropology", 
"Grand Valley State University Department Of Sociology", "Hohai University Department Of Sociology", 
"Indiana University Purdue University Indianapolis Department Of Sociology", 
"Johannes Kepler University Linz Department Of Sociology", "Kent State University Department Of Sociology", 
"Loyola Marymount University Department Of Sociology", "Martin Luther University Halle Wittenberg Department Of Sociology", 
"Maynooth University Department Of Sociology", "Middlesex University London Department Of Criminology And Sociology", 
"Nankai University Department Of Sociology", "National Tsing Hua University Institute Of Sociology", 
"Northern Illinois University Department Of Sociology", "Ohio University Department Of Sociology And Anthropology", 
"Old Dominion University Department Of Sociology And Criminal Justice", 
"Philipps University Marburg Institute Of Sociology", "Radford University Department Of Sociology", 
"Rutgers Newark Department Of Sociology And Anthropology", "Simon Fraser University Department Of Sociology And Anthropology", 
"Soas University Of London Department Of Anthropology And Sociology", 
"Southeast University Department Of Sociology", "Texas A M University Kingsville Department Of Psychology And Sociology", 
"The Open University Department Of Sociology", "The University Of Maine Department Of Sociology", 
"Tokyo Metropolitan University Department Of Social Sciences Sociology", 
"Toronto Metropolitan University Department Of Sociology", "Tu Darmstadt Institute Of Sociology", 
"Tu Dresden Institute Of Sociology", "Ulb Institute Of Sociology", 
"University Of Bucharest Faculty Of Sociology And Social Work", 
"University Of Cape Town Department Of Sociology", "University Of Cologne Institute For Medical Sociology Health Services Research And Rehabilitation Science", 
"University Of Erlangen Nuremberg Institute Of Sociology", "University Of Ljubljana Department Of Sociology", 
"University Of Lleida Department Of Geography And Sociology", 
"University Of Lodz Faculty Of Economics And Sociology", "University Of Manitoba Department Of Sociology And Criminology", 
"University Of Montreal Department Od Sociology", "University Of Nevada Reno Department Of Sociology", 
"University Of Pittsburgh Department Of Sociology", "University Of Plymouth Criminology Sociology And Anthropology Subject Area", 
"University Of Pretoria Department Of Sociology", "University Of The Witwatersrand Johannesburg Department Of Sociology", 
"University Of Valladolid Department Of Sociology And Social Work", 
"University Of Vermont Department Of Sociology", "University Of Warsaw Faculty Of Philosophy And Sociology", 
"University Of Warsaw Institute Of Sociology", "University Of Windsor Department Of Sociology Anthropology And Criminology", 
"Vassar College Department Of Sociology", "Wageningen University Research Sociology Of Development And Change Group", 
"Wheaton College Department Of Sociology And Anthropology", "William Mary Department Of Sociology", 
"Wuhan University School Of Sociology"), score = c(74, 64, 59, 
58, 57, 56, 53, 53, 49, 49, 48, 48, 47, 47, 46, 41, 40, 40, 40, 
38, 37, 36, 36, 36, 36, 35, 35, 34, 34, 33, 32, 32, 31, 31, 30, 
28, 27, 26, 26, 25, 24, 23, 23, 23, 22, 22, 22, 22, 22, 21, 21, 
20, 20, 20, 19, 18, 18, 18, 18, 18, 17, 17, 17, 17, 16, 16, 16, 
16, 15, 15, 15, 14, 14, 14, 14, 14, 14, 14, 14, 14, 13, 13, 13, 
13, 13, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 11, 11, 11, 
11, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 
9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 
7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)), row.names = c(NA, 
-319L),  class = c("spec_tbl_df", 
"tbl_df", "tbl", "data.frame"))

sample_editors.df <- structure(list(descriptions = c("Faisal Abbas - Sections: Human health - National University of Sciences and Technology - PAKISTAN", 
"Luca Maria Aiello - Sections: Human behavior and social complexity - IT University of Copenhagen: IT-Universitetet i Kobenhavn - SPAIN", 
"Shah Jamal Alam - Sections: Climate and natural hazards - Habib University - PAKISTAN", 
"Réka Albert - Sections: Concepts in complexity - Pennsylvania State University - UNITED STATES OF AMERICA", 
"Diego R. Amancio - Sections: Computational complexity - Universidade de Sao Paulo - BRAZIL", 
"Guillermo de Anda-Jáuregui - Sections: Human health - Instituto Nacional de Medicina Genómica: Instituto Nacional de Medicina Genomica - MEXICO", 
"Joshua Kiddy K. Asamoah - Sections: Human health - Kwame Nkrumah University of Science and Technology - GHANA", 
"Chloe Clifford Astbury - Sections: Human health - York University - CANADA", 
"Jennifer Badham - Sections: Human behavior and social complexity - Durham University - UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND", 
"Yiguang Bai - Sections: Computational complexity - Xidian University - CHINA", 
"Juan Gonzalo Barajas-Ramirez - Sections: Concepts in complexity - IPICYT: Instituto Potosino de Investigacion Cientifica y Tecnologica AC - MEXICO", 
"Marco Bastos - Sections: Human behavior and social complexity - University College Dublin - National University of Ireland: University College Dublin - IRELAND", 
"Rene C. Batac - Sections: Climate and natural hazards - De la Salle University - PHILIPPINES", 
"Francesco Battaglia - Sections: Human health - Radboud University - UNITED STATES OF AMERICA"
)), row.names = c(NA, -14L), class = c("tbl_df", "tbl", "data.frame"
))

```

```{r dict-matching}


sample_editors_plus.df <- dplyr::bind_rows(sample_editors.df,
                            tibble::tibble(descriptions=c("","Canada","ANGOLA rules!!", "ANTIGUA AND")))



res <- add_dict_matches(sample_editors_plus.df, 
                      col_map=c(text="descriptions"), dicts = c("iso3166","kantro"),
                     matchTypes = c("exact","starts","contains"),
                     matchFirstN = 2)  

res
```
